"""Copy the canonical conformance assets from the spec submodule into the package.

Used by `poe sync-spec-assets` for local development and CI testing. The hatch
build hook (hatch_build.py) handles inclusion in the wheel and sdist.

The assets are owned by open-feature/spec, not by this repository. Copying them
in at build time -- rather than committing copies -- means the spec revision this
package was built against is recorded by the submodule pin and nowhere else, so
the two cannot drift apart unnoticed. An *adopter* installing the wheel still
needs no submodule: the copies are inside the distribution.

Copying is the second half of the job. The first is making sure the submodule
working tree is at the revision the pin names, because **a rebase moves the
gitlink and not the working tree** -- see `checkout_pinned_spec`.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import warnings
from collections.abc import Callable, Sequence
from pathlib import Path

ROOT = Path(__file__).parent
SPEC_DIRNAME = "spec"
SPEC_ROOT = (ROOT / SPEC_DIRNAME).resolve()
ASSETS_PATH_IN_SPEC = "specification/assets/provider-tck"
SPEC_ASSETS = (SPEC_ROOT / ASSETS_PATH_IN_SPEC).resolve()
PACKAGE_REL = Path("src/openfeature/contrib/tools/tck")
DEST_BASE = ROOT / PACKAGE_REL

UNPINNED_ENV = "OPENFEATURE_TCK_SPEC_UNPINNED"
"""Set to run against whatever is checked out in the submodule, pin or no pin.

For the one workflow that legitimately wants it: drafting a change to the
canonical assets in a local spec checkout before there is a revision to pin. It
warns on every sync, and it names the revision actually in use, because a suite
running against assets nobody can identify must not be quiet about it.
"""

DO_NOT_EDIT = (
    "Generated by hatch_build_sync.py from the open-feature/spec submodule.\n"
    "DO NOT EDIT. Changes belong in open-feature/spec under\n"
    "specification/assets/provider-tck/, then bump the submodule pin.\n"
)

# (source directory or file, destination) relative to SPEC_ASSETS / DEST_BASE.
#
# "gherkin" copies to a directory of the same name on purpose, and the pair is not
# redundant: a canonical feature is identified by its path relative to the asset
# directory, so the destination name *is* the reported uri prefix. Renaming it
# locally -- it used to land in "features" -- silently renamed the uri, which is
# how this suite reported features/errors.feature for the file Go reports as
# gherkin/errors.feature. Keep the two equal.
TREES = [("gherkin", "gherkin"), ("flags", "flag_data")]
FILES = [("openapi/control-api.yaml", "control-api.yaml")]

GitRunner = Callable[[Sequence[str], Path], str | None]
"""Runs a git command in a directory and returns its output, or ``None`` if it failed.

A seam, so the decision `checkout_pinned_spec` makes can be tested without a
fixture repository on disk. Failure is ``None`` rather than an exception because
every caller here treats "git could not answer" as a state to report rather than
a crash: building from an unpacked sdist has no repository at all.
"""


def _run_git(args: Sequence[str], cwd: Path) -> str | None:
    try:
        completed = subprocess.run(  # noqa: S603
            ["git", *args],  # noqa: S607
            cwd=cwd,
            capture_output=True,
            check=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return completed.stdout.strip()


def pinned_revision(git: GitRunner = _run_git) -> str | None:
    """The spec revision the superproject's index records for the submodule.

    The index rather than ``HEAD``, because the index is what the next commit
    will record and so what a run is about to claim it tested against. ``None``
    when there is no repository to ask, which is ordinary: an sdist has none.
    """
    entry = git(["ls-files", "-s", "--", SPEC_DIRNAME], ROOT)
    if not entry:
        return None
    fields = entry.split()
    # "160000 <sha> 0<TAB>spec". Anything else is not a gitlink -- a plain
    # directory checked in under that name, most likely -- and there is no pin.
    if len(fields) < 2 or fields[0] != "160000":
        return None
    return fields[1]


def checkout_pinned_spec(git: GitRunner = _run_git) -> str | None:
    """Bring the submodule working tree to the revision the pin names.

    **This is the reason this function exists: a rebase moves the gitlink and
    not the submodule's working tree.** So a checkout can have a pin saying one
    revision and assets on disk from another, and nothing about the build says
    so. That is not hypothetical -- it happened here, the copied Gherkin was one
    pin behind the capability the suite was declaring, and a self-test of the
    enum against the assets is what caught it. That guard fires for one symptom.
    A pin that changes only the *content* of a scenario would pass every guard
    in this package and still run the wrong suite, which is what happened in
    another language: a whole adoption suite ran against stale assets and
    reported byte-identical numbers to the previous pass, and nothing failed and
    nothing warned.

    So the checkout is part of the copy rather than something the operator is
    expected to remember, and the copy is a dependency of the test task. The
    suite cannot run against assets it did not just fetch.

    Returns the pinned revision, or ``None`` when there is no pin to read.

    **When the pin cannot be read this warns rather than failing.** Building
    from an unpacked sdist is the ordinary case -- no repository, no pin, and
    the assets are already in the tree. The other case is a git checkout whose
    superproject this process cannot reach, which happens for a linked worktree
    whose ``.git`` file names a path in another filesystem namespace: git inside
    the submodule answers, git in the superproject does not. Warning rather than
    failing keeps that environment usable; the warning is what says the
    guarantee is not in force, and the remedy is to run the sync from a shell
    that can see the superproject.
    """
    if os.environ.get(UNPINNED_ENV):
        head = git(["rev-parse", "HEAD"], SPEC_ROOT)
        warnings.warn(
            f"{UNPINNED_ENV} is set: syncing the conformance assets from whatever "
            f"is checked out in {SPEC_ROOT} ({head or 'unknown revision'}) rather "
            f"than from the revision the submodule pin names. Nothing records "
            f"which questions this run asked",
            stacklevel=2,
        )
        return None

    pinned = pinned_revision(git)
    if pinned is None:
        if SPEC_ROOT.exists():
            warnings.warn(
                f"could not read the submodule pin for {SPEC_DIRNAME} from a git "
                f"index in {ROOT}, so the conformance assets are being copied from "
                f"the submodule working tree unverified. If this is a checkout "
                f"rather than an unpacked sdist, a rebase may have moved the pin "
                f"without moving that working tree: run `git submodule update "
                f"--init tools/openfeature-tck/spec` from a shell that can see the "
                f"superproject, then sync again",
                stacklevel=2,
            )
        return None

    head = git(["rev-parse", "HEAD"], SPEC_ROOT)
    if head == pinned:
        return pinned

    print(  # noqa: T201
        f"spec submodule is at {head or '(not checked out)'}, the pin names "
        f"{pinned}: checking out the pinned revision"
    )
    git(["submodule", "update", "--init", "--", SPEC_DIRNAME], ROOT)

    head = git(["rev-parse", "HEAD"], SPEC_ROOT)
    if head != pinned:
        msg = (
            f"the {SPEC_DIRNAME} submodule is at {head or '(not checked out)'} and "
            f"the pin names {pinned}, and `git submodule update --init` did not "
            f"move it. The assets would be from the wrong revision, so nothing is "
            f"copied. Most likely the pinned commit is not in the local object "
            f"store and could not be fetched; check network access to "
            f"open-feature/spec, or fetch it by hand. To copy from the working "
            f"tree anyway -- for drafting a spec change that has no revision yet "
            f"-- put {UNPINNED_ENV}=1 in the environment."
        )
        raise RuntimeError(msg)
    return pinned


REVISION_FILE = "spec_revision.json"
"""Which revision of the specification the copied assets came from.

Recorded at build time because the answer is only available at build time: the
submodule that holds it is not in the wheel, and a conformance report that cannot
name the revision it ran against cannot be compared with another. It is generated
by the same command that copies the assets, which is what keeps the two from
disagreeing.

Not committed, for the same reason the assets are not: the submodule pin is the
single record of which revision this package targets.
"""

UNKNOWN_REVISION = "unknown"
"""Seven characters, the minimum the report schema accepts.

A build that cannot reach git says it does not know rather than inventing a
commit, and still produces a document that validates. Which happens for real:
building from a source tarball has no ``.git`` to ask.
"""


def sync() -> None:
    checkout_pinned_spec()

    if not SPEC_ASSETS.exists():
        msg = (
            f"Conformance assets not found at {SPEC_ASSETS}. "
            "Make sure submodules are initialized: "
            "`git submodule update --init tools/openfeature-tck/spec`."
        )
        raise FileNotFoundError(msg)

    for src_name, dest_name in TREES:
        dest = DEST_BASE / dest_name
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(SPEC_ASSETS / src_name, dest)
        (dest / "DO-NOT-EDIT.txt").write_text(DO_NOT_EDIT, encoding="utf-8")

    for src_name, dest_name in FILES:
        dest = DEST_BASE / dest_name
        if dest.exists():
            dest.unlink()
        shutil.copy2(SPEC_ASSETS / src_name, dest)

    write_revision()


def write_revision() -> None:
    """Record the spec commit and the asset tree these copies came from.

    The tree hash is carried as well as the commit because it identifies the
    assets alone: it does not change when an unrelated part of the specification
    does, so two runs that executed identical assets report the same value even
    when pinned to different commits. It is also checkable rather than merely
    asserted, since ``git rev-parse <commit>:specification/assets/provider-tck``
    must reproduce it.
    """
    commit = _git("rev-parse", "HEAD") or UNKNOWN_REVISION
    tree = _git("rev-parse", f"HEAD:{ASSETS_PATH_IN_SPEC}") or ""
    (DEST_BASE / REVISION_FILE).write_text(
        json.dumps({"specRevision": commit, "assetsTree": tree}, indent=2) + "\n",
        encoding="utf-8",
    )


def _git(*args: str) -> str:
    """Run git inside the submodule, returning its output or an empty string.

    A build must not hard-fail because git is absent or the checkout is not a
    repository -- both are ordinary when building from an unpacked sdist. The
    failure is reported as a warning and the identity degrades to ``unknown``,
    which is legible in the resulting report rather than silently wrong.
    """
    command = ["git", "-C", str(SPEC_ROOT), *args]
    try:
        completed = subprocess.run(  # noqa: S603
            command, capture_output=True, check=True, text=True
        )
    except (OSError, subprocess.CalledProcessError) as error:
        warnings.warn(
            f"could not determine the spec revision ({' '.join(command)}: {error}); "
            f"conformance reports from this build will not name the revision they "
            f"ran against",
            stacklevel=2,
        )
        return ""
    return completed.stdout.strip()


if __name__ == "__main__":
    sync()
