"""Copy the canonical conformance assets from the spec submodule into the package.

Used by `poe sync-spec-assets` for local development and CI testing. The hatch
build hook (hatch_build.py) handles inclusion in the wheel and sdist.

The assets are owned by open-feature/spec, not by this repository. Copying them
in at build time -- rather than committing copies -- means the spec revision this
package was built against is recorded by the submodule pin and nowhere else, so
the two cannot drift apart unnoticed. An *adopter* installing the wheel still
needs no submodule: the copies are inside the distribution.
"""

import shutil
from pathlib import Path

ROOT = Path(__file__).parent
SPEC_ASSETS = (ROOT / "spec/specification/assets/provider-tck").resolve()
PACKAGE_REL = Path("src/openfeature/contrib/tools/tck")
DEST_BASE = ROOT / PACKAGE_REL

DO_NOT_EDIT = (
    "Generated by hatch_build_sync.py from the open-feature/spec submodule.\n"
    "DO NOT EDIT. Changes belong in open-feature/spec under\n"
    "specification/assets/provider-tck/, then bump the submodule pin.\n"
)

# (source directory or file, destination) relative to SPEC_ASSETS / DEST_BASE.
#
# "gherkin" copies to a directory of the same name on purpose, and the pair is not
# redundant: a canonical feature is identified by its path relative to the asset
# directory, so the destination name *is* the reported uri prefix. Renaming it
# locally -- it used to land in "features" -- silently renamed the uri, which is
# how this suite reported features/errors.feature for the file Go reports as
# gherkin/errors.feature. Keep the two equal.
TREES = [("gherkin", "gherkin"), ("flags", "flag_data")]
FILES = [("openapi/control-api.yaml", "control-api.yaml")]


def sync() -> None:
    if not SPEC_ASSETS.exists():
        msg = (
            f"Conformance assets not found at {SPEC_ASSETS}. "
            "Make sure submodules are initialized: "
            "`git submodule update --init tools/openfeature-tck/spec`."
        )
        raise FileNotFoundError(msg)

    for src_name, dest_name in TREES:
        dest = DEST_BASE / dest_name
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(SPEC_ASSETS / src_name, dest)
        (dest / "DO-NOT-EDIT.txt").write_text(DO_NOT_EDIT, encoding="utf-8")

    for src_name, dest_name in FILES:
        dest = DEST_BASE / dest_name
        if dest.exists():
            dest.unlink()
        shutil.copy2(SPEC_ASSETS / src_name, dest)


if __name__ == "__main__":
    sync()
