# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Merge

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["python:3.8", "python:3.9", "python:3.10", "python:3.11"]
    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: bufbuild/buf-setup-action@v1.27.1
        with:
          github_token: ${{ github.token }}

      - name: Cache virtualenvironment
        uses: actions/cache@v2
        with:
          path: ~/.venv
          key: ${{ hashFiles('requirements.txt') }}

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Create and activate Virtualenv
        run: |
          [ ! -d ".venv" ] && python -m venv .venv
          . .venv/bin/activate

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Generate flagd protobuf files
        run: |
          cd schemas
          buf generate buf.build/open-feature/flagd --template protobuf/buf.gen.python.yaml
          cd ../
          rm -rf openfeature/contrib/providers/flagd/proto
          mv proto/python openfeature/contrib/providers/flagd/proto
          sed -i.bak 's/^from schema.v1 import/from . import/' openfeature/contrib/providers/flagd/proto/schema/v1/*.py
          rm openfeature/contrib/providers/flagd/proto/schema/v1/*.bak
          rmdir proto

      - name: Test with pytest
        run: coverage run --omit="*/test*" -m pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e0fbd592d323cb2991fb586fdd260734fcb41fcb
        with:
          flags: unittests # optional
          name: coverage # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
